version: 2

sources:
  - name: olist_raw
    database: OLIST_DW
    schema: RAW
    freshness:
      warn_after: {count: 25, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: "order_purchase_timestamp"
    tables:
      - name: fct_orders
        columns:
          - name: order_id
            tests:
              - not_null
              - unique
          - name: customer_id
            tests: [not_null]
          - name: price
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  max_value: 15000
          - name: order_status
            tests:
              - accepted_values:
                  values: ['delivered','shipped','processing',
                           'canceled','unavailable','invoiced',
                           'approved','created']
          - name: order_year_month
            tests: [not_null]

      - name: dim_customers
        columns:
          - name: customer_id
            tests: [not_null, unique]
          - name: state
            tests: [not_null]

      - name: dim_products
        columns:
          - name: product_id
            tests: [not_null, unique]

      - name: dim_sellers
        columns:
          - name: seller_id
            tests: [not_null, unique]

models:
  - name: fct_orders
    description: "Order-item fact table — incremental"
    config:
      contract:
        enforced: true
    columns:
      - name: order_id
        data_type: varchar
        tests: [not_null]
      - name: order_item_id
        data_type: integer
        tests: [not_null]
      - name: order_item_revenue
        data_type: float
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 20000
      - name: order_year_month
        data_type: varchar
        tests: [not_null]

  - name: fct_monthly_revenue
    columns:
      - name: order_year_month
        tests: [not_null]
      - name: revenue_brl
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 50000000
